# Generated by Django 4.0.7 on 2022-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Educational_details',
            field=models.CharField(default='I have worked on projects of this scale which makes me perfect fit for this role. please do consider me', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
