# Generated by Django 4.0.7 on 2022-09-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_educational_details_person_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Resume',
            field=models.FileField(default='/Users/manas/Downloads/Lekhit Borole resume 18th August 1.pdf', max_length=256, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
