# Generated by Django 4.0.7 on 2022-09-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_person_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Resume',
            field=models.FileField(max_length=256, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
