# Generated by Django 4.0.7 on 2022-09-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Contact_Number',
            field=models.CharField(default='9999999999', max_length=10),
            preserve_default=False,
        ),
    ]
