# Generated by Django 4.0.7 on 2022-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_person_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Resume',
            field=models.FileField(blank=True, max_length=256, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
