# Generated by Django 4.0.7 on 2022-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_person_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Status',
            field=models.CharField(choices=[('accepeted', 'accepeted'), ('unaccepeted', 'unaccepted')], default='accepted', max_length=20),
        ),
    ]
