# Generated by Django 4.0.7 on 2022-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_alter_person_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
